#!/usr/bin/env python3
r"""
current_patch_compat_modern_deps.py

Modern dependency compatibility patch for the current paper sandbox.

Purpose
-------
The official bgmat repo's setup.py currently pins older dependency versions
(e.g. numpy==1.25.2, matplotlib==3.7.0, jax==0.4.32). That can collide with
modern Python 3.12 environments.

This script creates a small, explicit compatibility fork patch:

- backs up bgmat/setup.py
- rewrites install_requires to modern Python-3.12-friendly dependency specs
- writes requirements_modern_py312.txt at repo root
- writes COMPATIBILITY_PATCH_REPORT.md at repo root

No absolute local paths are used.

Important
---------
This is NOT the same thing as exact environment reproduction.
This is a modern-compatibility sandbox path.

Run from the probe directory:

  python .\current_patch_compat_modern_deps.py --apply

Then install (from the probe directory):

  python -m pip install -U -r .\requirements_modern_py312.txt
  python -m pip install --no-build-isolation --no-deps -e .\bgmat
  python .\current_probe_03_official_repo_smoke.py --import-smoke --extra-import bgmat

To preview only:

  python .\current_patch_compat_modern_deps.py
"""

from __future__ import annotations

import argparse
import datetime as _dt
from pathlib import Path
import re
import sys
from typing import List


REPO_ROOT = Path(__file__).resolve().parent.parent


MODERN_DEPS: List[str] = [
    # Core numerical stack. Let pip pick current wheels for this Python.
    "numpy>=2.0,<3",
    "scipy>=1.14,<2",
    "matplotlib>=3.9,<4",

    # JAX stack. On native Windows this is expected to be CPU JAX.
    # For GPU JAX, use WSL/Linux and the official jax[cuda...] route.
    "jax",

    # Haiku installs as dm-haiku but imports as haiku.
    "dm-haiku",

    # Probability distributions in JAX.
    "distrax>=0.1.9",

    # Molecular simulation toolkit.
    "openmm",

    # Common utilities likely used by experiments.
    "ase>=3.23",
    "tqdm>=4.66",
    "pbr<6",
]


def now_stamp() -> str:
    return _dt.datetime.now().strftime("%Y%m%d_%H%M%S")


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT.resolve())).replace("\\", "/")
    except Exception:
        return str(path).replace("\\", "/")


def deps_block(indent: str = "        ") -> str:
    return "\n".join(f'{indent}"{dep}",' for dep in MODERN_DEPS)


def patch_setup_py(text: str) -> tuple[str, str]:
    """
    Replace install_requires=[...] with MODERN_DEPS.

    Returns (new_text, method).
    """
    pattern = re.compile(r"(install_requires\s*=\s*)\[(.*?)\]", re.DOTALL)
    match = pattern.search(text)
    if match:
        before = match.group(1)
        line_start = text.rfind("\n", 0, match.start()) + 1
        leading = re.match(r"\s*", text[line_start:match.start()]).group(0)
        item_indent = leading + "    "
        replacement = before + "[\n" + deps_block(item_indent) + "\n" + leading + "]"
        return text[:match.start()] + replacement + text[match.end():], "replaced_existing_install_requires"

    setup_call = re.search(r"setup\s*\(", text)
    if not setup_call:
        raise RuntimeError("Could not find setup(...) call in setup.py")

    packages_pat = re.compile(r"(packages\s*=\s*find_packages\s*\(\s*\)\s*,?)")
    pm = packages_pat.search(text)
    if pm:
        insert_at = pm.end()
        insertion = "\n    install_requires=[\n" + deps_block("        ") + "\n    ],"
        return text[:insert_at] + insertion + text[insert_at:], "inserted_after_find_packages"

    raise RuntimeError("Could not find install_requires or packages=find_packages() insertion point")


def write_requirements(path: Path) -> None:
    path.write_text(
        "# Modern Python 3.12 compatibility requirements for the current paper sandbox.\n"
        "# Generated by current_patch_compat_modern_deps.py.\n"
        "# This is a compatibility fork path, not exact historical reproduction.\n\n"
        + "\n".join(MODERN_DEPS)
        + "\n",
        encoding="utf-8",
    )


def write_report(path: Path, official_repo: Path, setup_path: Path, backup_path: Path | None, applied: bool, method: str, changed: bool) -> None:
    lines = [
        "# Compatibility patch report",
        "",
        "This repo has been prepared for a modern Python 3.12 sandbox path.",
        "",
        "## Scope",
        "",
        "- This patch updates dependency specs in the official-code checkout.",
        "- It is meant for exploratory sandboxing, not exact archival reproduction.",
        "- Generated run outputs should stay in `probe_runs/` and usually remain uncommitted.",
        "",
        "## Paths",
        "",
        f"- Official repo: `{rel(official_repo)}`",
        f"- Patched setup.py: `{rel(setup_path)}`",
        f"- Backup setup.py: `{rel(backup_path) if backup_path else ''}`",
        "",
        "## Status",
        "",
        f"- Applied: `{applied}`",
        f"- Changed setup.py: `{changed}`",
        f"- Patch method: `{method}`",
        "",
        "## Modern dependency set",
        "",
    ]
    for dep in MODERN_DEPS:
        lines.append(f"- `{dep}`")
    lines += [
        "",
        "## Install commands",
        "",
        "Run from the probe directory:",
        "",
        "```powershell",
        "python -m pip install -U -r .\\requirements_modern_py312.txt",
        "python -m pip install --no-build-isolation --no-deps -e .\\bgmat",
        "python .\\current_probe_03_official_repo_smoke.py --import-smoke --extra-import bgmat",
        "```",
        "",
        "## Rollback",
        "",
        "Replace `bgmat/setup.py` with the backup file listed above.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Patch bgmat/setup.py for modern Python 3.12 dependency compatibility.")
    p.add_argument("--official-repo", default="bgmat", help="Official repo folder relative to this repo root unless absolute.")
    p.add_argument("--apply", action="store_true", help="Actually write changes. Without this, dry-run only.")
    p.add_argument("--force", action="store_true", help="Patch even if setup.py already appears patched.")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    official_repo = Path(args.official_repo).expanduser()
    if not official_repo.is_absolute():
        official_repo = REPO_ROOT / official_repo

    setup_path = official_repo / "setup.py"
    req_path = REPO_ROOT / "requirements_modern_py312.txt"
    report_path = REPO_ROOT / "COMPATIBILITY_PATCH_REPORT.md"

    print("=" * 100)
    print("CURRENT PAPER — MODERN DEPENDENCY COMPATIBILITY PATCH")
    print("=" * 100)
    print(f"[ROOT]          {REPO_ROOT}")
    print(f"[OFFICIAL REPO] {rel(official_repo)}")
    print(f"[SETUP]         {rel(setup_path)}")
    print(f"[MODE]          {'APPLY' if args.apply else 'DRY RUN'}")

    if not setup_path.exists():
        print(f"[ERROR] Missing setup.py: {rel(setup_path)}", file=sys.stderr)
        sys.exit(2)

    old = setup_path.read_text(encoding="utf-8", errors="replace")
    new, method = patch_setup_py(old)
    changed = new != old

    if not changed and not args.force:
        print("[OK] setup.py text is already unchanged by this patch.")
    else:
        print(f"[PATCH] method={method}")
        print("[DEPS]")
        for dep in MODERN_DEPS:
            print(f"  - {dep}")

    backup_path = None
    if args.apply:
        backup_path = setup_path.with_name(f"setup.py.legacy_pins_backup_{now_stamp()}")
        if changed or args.force:
            backup_path.write_text(old, encoding="utf-8")
            setup_path.write_text(new, encoding="utf-8")
            print(f"[WROTE] backup: {rel(backup_path)}")
            print(f"[WROTE] patched: {rel(setup_path)}")
        write_requirements(req_path)
        write_report(report_path, official_repo, setup_path, backup_path, applied=True, method=method, changed=changed)
        print(f"[WROTE] {rel(req_path)}")
        print(f"[WROTE] {rel(report_path)}")
    else:
        write_report(report_path, official_repo, setup_path, backup_path, applied=False, method=method, changed=changed)
        print("[DRY] would write patched setup.py")
        print(f"[DRY] would write {rel(req_path)}")
        print(f"[WROTE] dry-run report: {rel(report_path)}")

    print("\nNext:")
    if not args.apply:
        print("  python .\\current_patch_compat_modern_deps.py --apply")
    else:
        print("  python -m pip install -U -r .\\requirements_modern_py312.txt")
        print("  python -m pip install --no-build-isolation --no-deps -e .\\bgmat")
        print("  python .\\current_probe_03_official_repo_smoke.py --import-smoke --extra-import bgmat")


if __name__ == "__main__":
    main()
