import DegreeSixKeller.JacobianKeller
import DegreeSixKeller.FunctionFieldSpike
import DegreeSixKeller.GenericDegreeGeneratorSpike
import Mathlib.FieldTheory.Relrank
import Mathlib.RingTheory.AlgebraicIndependent.Adjoin
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental

/-!
# Generic degree of the degree-six Keller family

The generic degree of a polynomial map is defined here as the degree of the
canonical extension of rational function fields: the source is the fraction
field of the three-variable polynomial ring and the base is the intermediate
field generated by the three coordinate polynomials.

For `FhPolynomial h` we construct the rational chart `(s,p,q)`, prove that it
generates the source function field, and transport that chart to the staged
`Complex(p,q)(s)` model established by the function-field spikes.  In that
model the third target coordinate is the degree-six inverse generator.
-/

set_option autoImplicit false

namespace DegreeSixKeller

open Function IntermediateField algebraAdjoinAdjoin MvPolynomial Polynomial Set
open scoped IntermediateField Polynomial RatFunc

noncomputable section

namespace GenericDegree

open DegreeSixKeller.FunctionFieldSpike
open DegreeSixKeller.GenericDegreeGeneratorSpike

/-- The canonical rational function field of the source affine three-space. -/
abbrev SourceFunctionField :=
  DegreeSixKeller.FunctionFieldSpike.SourceFunctionField

/-- Inclusion of source polynomials into the source rational function field. -/
abbrev sourcePolynomialInclusion :
    MvPolynomial (Fin 3) Complex →ₐ[Complex] SourceFunctionField :=
  DegreeSixKeller.FunctionFieldSpike.sourcePolynomialInclusion

/-- Canonical rational source coordinates. -/
abbrev sourceCoordinate : Fin 3 → SourceFunctionField :=
  DegreeSixKeller.FunctionFieldSpike.sourceCoordinate

/-- The rational function represented by one coordinate polynomial. -/
def coordinateRationalFunction
    (P : PolynomialMap3) (i : Fin 3) : SourceFunctionField :=
  sourcePolynomialInclusion (P i)

/-- The subfield generated by the coordinate functions of a polynomial map. -/
def coordinateFunctionField (P : PolynomialMap3) :
    IntermediateField Complex SourceFunctionField :=
  IntermediateField.adjoin Complex (Set.range (coordinateRationalFunction P))

/-- Generic degree as the genuine degree of the induced function-field
extension.  Mathlib's `finrank` is `0` for an infinite extension. -/
def genericDegree (P : PolynomialMap3) : Nat :=
  Module.finrank (coordinateFunctionField P) SourceFunctionField

/-- The canonical source coordinates generate the full rational function
field. -/
def sourceCoordinateFunctionField :
    IntermediateField Complex SourceFunctionField :=
  IntermediateField.adjoin Complex (Set.range sourceCoordinate)

@[simp] private theorem sourcePolynomialInclusion_natCast (n : Nat) :
    sourcePolynomialInclusion (n : MvPolynomial (Fin 3) Complex) =
      (n : SourceFunctionField) := by
  exact map_natCast sourcePolynomialInclusion n

@[simp] private theorem sourcePolynomialInclusion_ofNat
    (n : Nat) [n.AtLeastTwo] :
    sourcePolynomialInclusion
        (OfNat.ofNat n : MvPolynomial (Fin 3) Complex) =
      (OfNat.ofNat n : SourceFunctionField) := by
  exact map_ofNat sourcePolynomialInclusion n

@[simp] private theorem sourcePolynomialInclusion_C (c : Complex) :
    sourcePolynomialInclusion (MvPolynomial.C c) =
      algebraMap Complex SourceFunctionField c := by
  exact sourcePolynomialInclusion.commutes c

@[simp] private theorem algebraMap_Complex_natCast (n : Nat) :
    algebraMap Complex SourceFunctionField (n : Complex) =
      (n : SourceFunctionField) := by
  exact map_natCast (algebraMap Complex SourceFunctionField) n

@[simp] private theorem algebraMap_Complex_ofNat
    (n : Nat) [n.AtLeastTwo] :
    algebraMap Complex SourceFunctionField
        (OfNat.ofNat n : Complex) =
      (OfNat.ofNat n : SourceFunctionField) := by
  exact map_ofNat (algebraMap Complex SourceFunctionField) n

@[simp] private theorem sourcePolynomialInclusion_sourceX :
    sourcePolynomialInclusion sourceX = sourceCoordinate 0 := rfl

@[simp] private theorem sourcePolynomialInclusion_sourceY :
    sourcePolynomialInclusion sourceY = sourceCoordinate 1 := rfl

@[simp] private theorem sourcePolynomialInclusion_sourceZ :
    sourcePolynomialInclusion sourceZ = sourceCoordinate 2 := rfl

private theorem sourcePolynomial_mem_sourceCoordinateFunctionField
    (f : MvPolynomial (Fin 3) Complex) :
    sourcePolynomialInclusion f ∈ sourceCoordinateFunctionField := by
  induction f using MvPolynomial.induction_on with
  | C c =>
      rw [sourcePolynomialInclusion_C]
      exact sourceCoordinateFunctionField.algebraMap_mem c
  | add f g hf hg =>
      simpa only [map_add] using sourceCoordinateFunctionField.add_mem hf hg
  | mul_X f i hf =>
      have hXi : sourcePolynomialInclusion (MvPolynomial.X i) ∈
          sourceCoordinateFunctionField := by
        exact IntermediateField.subset_adjoin Complex
          (Set.range sourceCoordinate) ⟨i, rfl⟩
      simpa only [map_mul] using
        sourceCoordinateFunctionField.mul_mem hf hXi

theorem sourceCoordinateFunctionField_eq_top :
    sourceCoordinateFunctionField = ⊤ := by
  rw [eq_top_iff]
  intro z _hz
  obtain ⟨a, b, _hb, rfl⟩ :=
    IsFractionRing.div_surjective (MvPolynomial (Fin 3) Complex) z
  exact sourceCoordinateFunctionField.div_mem
    (sourcePolynomial_mem_sourceCoordinateFunctionField a)
    (sourcePolynomial_mem_sourceCoordinateFunctionField b)

/-! ## Rational chart for the family -/

/-- Rational lift of the marked factor `A`. -/
def sourceA : SourceFunctionField :=
  sourcePolynomialInclusion baseAPolynomial

/-- Rational lift of the marked factor `B`. -/
def sourceB : SourceFunctionField :=
  sourcePolynomialInclusion baseBPolynomial

/-- Rational lift of the undeformed second coordinate. -/
def sourceBaseQ : SourceFunctionField :=
  sourcePolynomialInclusion baseQPolynomial

/-- Rational lift of the undeformed third coordinate. -/
def sourceBaseR : SourceFunctionField :=
  sourcePolynomialInclusion baseRPolynomial

/-- Rational lift of `h(P)`. -/
def sourceDeformation (h : Complex[X]) : SourceFunctionField :=
  sourcePolynomialInclusion (deformationPolynomial h)

/-- First target coordinate in the source function field. -/
def FhSourceP (h : Complex[X]) : SourceFunctionField :=
  coordinateRationalFunction (FhPolynomial h) 0

/-- Second target coordinate in the source function field. -/
def FhSourceQ (h : Complex[X]) : SourceFunctionField :=
  coordinateRationalFunction (FhPolynomial h) 1

/-- Third target coordinate in the source function field. -/
def FhSourceR (h : Complex[X]) : SourceFunctionField :=
  coordinateRationalFunction (FhPolynomial h) 2

/-- The rational chart coordinate `s = x/A`. -/
def FhSourceS : SourceFunctionField :=
  sourceCoordinate 0 / sourceA

/-- The chart correction in the second target coordinate. -/
def FhSourcePhi (h : Complex[X]) : SourceFunctionField :=
  3 * FhSourceP h * FhSourceS +
    FhSourceP h ^ 6 * sourceDeformation h * FhSourceS ^ 4

/-- The chart correction in the third target coordinate. -/
def FhSourceTheta (h : Complex[X]) : SourceFunctionField :=
  FhSourceP h * FhSourceS ^ 3 +
    (2 / 3 : SourceFunctionField) * FhSourceP h ^ 6 *
      sourceDeformation h * FhSourceS ^ 6

/-- Reconstructed source `y` in the rational chart. -/
def FhReconstructionY (h : Complex[X]) : SourceFunctionField :=
  FhSourceQ h - FhSourcePhi h

/-- Reconstruction denominator `D = 1 - sy`. -/
def FhReconstructionD (h : Complex[X]) : SourceFunctionField :=
  1 - FhSourceS * FhReconstructionY h

/-- Rational reconstruction of the three source coordinates from `(p,q,s)`. -/
def FhRationalReconstruction (h : Complex[X]) :
    Fin 3 → SourceFunctionField
  | 0 => FhSourceS / FhReconstructionD h
  | 1 => FhReconstructionY h
  | 2 =>
      FhSourceP h * FhReconstructionD h ^ 3 -
        FhReconstructionY h ^ 2 *
          (4 - FhSourceS * FhReconstructionY h) * FhReconstructionD h

/-- The ordered chart `(s,p,q)`.  This order matches Mathlib's
`MvPolynomial.finSuccEquiv`: its first coordinate becomes `RatFunc.X` and
the remaining two become the coefficient-field coordinates. -/
def FhChartCoordinates (h : Complex[X]) : Fin 3 → SourceFunctionField
  | 0 => FhSourceS
  | 1 => FhSourceP h
  | 2 => FhSourceQ h

/-- Subfield generated by the rational chart. -/
def FhChartFunctionField (h : Complex[X]) :
    IntermediateField Complex SourceFunctionField :=
  IntermediateField.adjoin Complex (Set.range (FhChartCoordinates h))

theorem sourceA_eq :
    sourceA = 1 + sourceCoordinate 0 * sourceCoordinate 1 := by
  simp [sourceA, baseAPolynomial]

theorem sourceB_eq :
    sourceB = sourceA ^ 2 * sourceCoordinate 2 +
      sourceCoordinate 1 ^ 2 * (4 + 3 * sourceCoordinate 0 * sourceCoordinate 1) := by
  simp only [sourceB, sourceA, baseBPolynomial, baseAPolynomial,
    map_add, map_mul, map_pow, map_one,
    sourcePolynomialInclusion_sourceX,
    sourcePolynomialInclusion_sourceY,
    sourcePolynomialInclusion_sourceZ,
    sourcePolynomialInclusion_C]
  rw [map_ofNat (algebraMap Complex SourceFunctionField) 4,
    map_ofNat (algebraMap Complex SourceFunctionField) 3]

theorem FhSourceP_eq (h : Complex[X]) :
    FhSourceP h = sourceA * sourceB := by
  simp [FhSourceP, coordinateRationalFunction, FhPolynomial_zero,
    pCoordPolynomial, sourceA, sourceB]

@[simp] theorem sourceDeformation_eq_aeval (h : Complex[X]) :
    sourceDeformation h = Polynomial.aeval (FhSourceP h) h := by
  unfold sourceDeformation deformationPolynomial FhSourceP
    coordinateRationalFunction
  rw [FhPolynomial_zero, Polynomial.aeval_def]
  change sourcePolynomialInclusion.toRingHom
      (h.eval₂ MvPolynomial.C pCoordPolynomial) =
    h.eval₂ (algebraMap Complex SourceFunctionField)
      (sourcePolynomialInclusion pCoordPolynomial)
  rw [Polynomial.hom_eval₂]
  congr 1

theorem sourceBaseQ_eq :
    sourceBaseQ = sourceCoordinate 1 + 3 * sourceCoordinate 0 * sourceB := by
  simp only [sourceBaseQ, baseQPolynomial, sourceB, map_add, map_mul,
    sourcePolynomialInclusion_sourceX,
    sourcePolynomialInclusion_sourceY,
    sourcePolynomialInclusion_C]
  rw [map_ofNat (algebraMap Complex SourceFunctionField) 3]

theorem sourceBaseR_eq :
    sourceBaseR = 2 * sourceCoordinate 0 -
      3 * sourceCoordinate 0 ^ 2 * sourceCoordinate 1 -
      sourceCoordinate 0 ^ 3 * sourceCoordinate 2 := by
  simp only [sourceBaseR, baseRPolynomial, map_sub, map_mul, map_pow,
    sourcePolynomialInclusion_sourceX,
    sourcePolynomialInclusion_sourceY,
    sourcePolynomialInclusion_sourceZ,
    sourcePolynomialInclusion_C]
  rw [map_ofNat (algebraMap Complex SourceFunctionField) 2,
    map_ofNat (algebraMap Complex SourceFunctionField) 3]

theorem FhSourceQ_eq (h : Complex[X]) :
    FhSourceQ h = sourceBaseQ +
      sourceA ^ 2 * sourceCoordinate 0 ^ 4 * sourceB ^ 6 *
        sourceDeformation h := by
  rw [FhSourceQ, coordinateRationalFunction, FhPolynomial_one]
  unfold qCoordPolynomial sourceBaseQ sourceA sourceB sourceDeformation
  simp only [map_add, map_mul, map_pow,
    sourcePolynomialInclusion_sourceX]

theorem FhSourceR_eq (h : Complex[X]) :
    FhSourceR h = sourceBaseR -
      (2 / 3 : SourceFunctionField) * sourceCoordinate 0 ^ 6 *
        sourceB ^ 6 * sourceDeformation h := by
  rw [FhSourceR, coordinateRationalFunction, FhPolynomial_two]
  unfold rCoordPolynomial sourceBaseR sourceB sourceDeformation
  simp only [map_sub, map_mul, map_pow,
    sourcePolynomialInclusion_sourceX, sourcePolynomialInclusion_C]
  have hc : algebraMap Complex SourceFunctionField (2 / 3 : Complex) =
      (2 / 3 : SourceFunctionField) := by
    change algebraMap Complex SourceFunctionField
        ((2 : Complex) * (3 : Complex)⁻¹) =
      (2 : SourceFunctionField) * (3 : SourceFunctionField)⁻¹
    rw [map_mul, map_inv₀,
      map_ofNat (algebraMap Complex SourceFunctionField) 2,
      map_ofNat (algebraMap Complex SourceFunctionField) 3]
  rw [hc]

theorem sourceA_ne_zero : sourceA ≠ 0 := by
  have hpoly : baseAPolynomial ≠ 0 := by
    intro hzero
    have heval := congrArg
      (MvPolynomial.eval (fun _ : Fin 3 => (0 : Complex))) hzero
    simp [baseAPolynomial, sourceX, sourceY] at heval
  exact (map_ne_zero_iff sourcePolynomialInclusion
    (FaithfulSMul.algebraMap_injective
      (MvPolynomial (Fin 3) Complex) SourceFunctionField)).mpr hpoly

/-- The chart variable satisfies `sA=x`. -/
theorem FhSourceS_mul_sourceA :
    FhSourceS * sourceA = sourceCoordinate 0 := by
  unfold FhSourceS
  exact div_mul_cancel₀ _ sourceA_ne_zero

/-- The second target coordinate has the rational chart form `q=y+φ`. -/
theorem FhSourceQ_chart (h : Complex[X]) :
    FhSourceQ h = sourceCoordinate 1 + FhSourcePhi h := by
  have hlinear :
      3 * sourceCoordinate 0 * sourceB =
        3 * FhSourceP h * FhSourceS := by
    rw [FhSourceP_eq]
    unfold FhSourceS
    field_simp [sourceA_ne_zero]
  have hdeform :
      sourceA ^ 2 * sourceCoordinate 0 ^ 4 * sourceB ^ 6 =
        FhSourceP h ^ 6 * FhSourceS ^ 4 := by
    rw [FhSourceP_eq]
    unfold FhSourceS
    field_simp [sourceA_ne_zero]
  rw [FhSourceQ_eq, sourceBaseQ_eq]
  unfold FhSourcePhi
  rw [hlinear, hdeform]
  ring

@[simp] theorem FhReconstructionY_eq (h : Complex[X]) :
    FhReconstructionY h = sourceCoordinate 1 := by
  unfold FhReconstructionY
  rw [FhSourceQ_chart]
  ring

/-- The rational reconstruction denominator is exactly `A⁻¹`. -/
@[simp] theorem FhReconstructionD_eq (h : Complex[X]) :
    FhReconstructionD h = sourceA⁻¹ := by
  unfold FhReconstructionD FhSourceS
  rw [FhReconstructionY_eq]
  calc
    1 - sourceCoordinate 0 / sourceA * sourceCoordinate 1 =
        (sourceA - sourceCoordinate 0 * sourceCoordinate 1) / sourceA := by
      field_simp [sourceA_ne_zero]
    _ = 1 / sourceA := by
      rw [sourceA_eq]
      ring
    _ = sourceA⁻¹ := one_div _

/-- The third target coordinate has the rational chart form
`r=2s-ys²-θ`. -/
theorem FhSourceR_chart (h : Complex[X]) :
    FhSourceR h =
      2 * FhSourceS - sourceCoordinate 1 * FhSourceS ^ 2 -
        FhSourceTheta h := by
  have hbase : sourceBaseR =
      2 * FhSourceS - sourceCoordinate 1 * FhSourceS ^ 2 -
        FhSourceP h * FhSourceS ^ 3 := by
    rw [sourceBaseR_eq, FhSourceP_eq]
    unfold FhSourceS
    rw [sourceB_eq]
    field_simp [sourceA_ne_zero]
    rw [sourceA_eq]
    ring
  have hdeform : sourceCoordinate 0 ^ 6 * sourceB ^ 6 =
      FhSourceP h ^ 6 * FhSourceS ^ 6 := by
    rw [FhSourceP_eq]
    unfold FhSourceS
    field_simp [sourceA_ne_zero]
  have hdeformFull :
      (2 / 3 : SourceFunctionField) * sourceCoordinate 0 ^ 6 *
          sourceB ^ 6 * sourceDeformation h =
        (2 / 3 : SourceFunctionField) * FhSourceP h ^ 6 *
          sourceDeformation h * FhSourceS ^ 6 := by
    calc
      (2 / 3 : SourceFunctionField) * sourceCoordinate 0 ^ 6 *
            sourceB ^ 6 * sourceDeformation h =
          (2 / 3 : SourceFunctionField) *
            (sourceCoordinate 0 ^ 6 * sourceB ^ 6) *
              sourceDeformation h := by ring
      _ = (2 / 3 : SourceFunctionField) *
            (FhSourceP h ^ 6 * FhSourceS ^ 6) *
              sourceDeformation h := by rw [hdeform]
      _ = (2 / 3 : SourceFunctionField) * FhSourceP h ^ 6 *
            sourceDeformation h * FhSourceS ^ 6 := by ring
  rw [FhSourceR_eq, hbase]
  unfold FhSourceTheta
  rw [hdeformFull]
  ring

/-- The third target coordinate is the inverse polynomial evaluated at the
chart root. -/
theorem FhSourceR_inverseEquation (h : Complex[X]) :
    FhSourceR h =
      (1 / 3 : SourceFunctionField) * FhSourceP h ^ 6 *
          sourceDeformation h * FhSourceS ^ 6 +
        2 * FhSourceP h * FhSourceS ^ 3 -
        FhSourceQ h * FhSourceS ^ 2 + 2 * FhSourceS := by
  rw [FhSourceR_chart, FhSourceQ_chart]
  unfold FhSourcePhi FhSourceTheta
  ring

@[simp] theorem FhRationalReconstruction_zero (h : Complex[X]) :
    FhRationalReconstruction h 0 = sourceCoordinate 0 := by
  unfold FhRationalReconstruction
  rw [FhReconstructionD_eq]
  unfold FhSourceS
  rw [div_div, mul_inv_cancel₀ sourceA_ne_zero, div_one]

@[simp] theorem FhRationalReconstruction_one (h : Complex[X]) :
    FhRationalReconstruction h 1 = sourceCoordinate 1 := by
  exact FhReconstructionY_eq h

@[simp] theorem FhRationalReconstruction_two (h : Complex[X]) :
    FhRationalReconstruction h 2 = sourceCoordinate 2 := by
  unfold FhRationalReconstruction
  rw [FhReconstructionD_eq, FhReconstructionY_eq, FhSourceP_eq]
  unfold FhSourceS
  rw [sourceB_eq]
  field_simp [sourceA_ne_zero]
  rw [sourceA_eq]
  ring

/-- The rational reconstruction recovers every source coordinate. -/
theorem FhRationalReconstruction_eq_sourceCoordinate
    (h : Complex[X]) :
    FhRationalReconstruction h = sourceCoordinate := by
  funext i
  fin_cases i <;> simp

theorem FhSourceS_mem_chartField (h : Complex[X]) :
    FhSourceS ∈ FhChartFunctionField h := by
  exact IntermediateField.subset_adjoin Complex
    (Set.range (FhChartCoordinates h)) ⟨0, rfl⟩

theorem FhSourceP_mem_chartField (h : Complex[X]) :
    FhSourceP h ∈ FhChartFunctionField h := by
  exact IntermediateField.subset_adjoin Complex
    (Set.range (FhChartCoordinates h)) ⟨1, rfl⟩

theorem FhSourceQ_mem_chartField (h : Complex[X]) :
    FhSourceQ h ∈ FhChartFunctionField h := by
  exact IntermediateField.subset_adjoin Complex
    (Set.range (FhChartCoordinates h)) ⟨2, rfl⟩

theorem aeval_FhSourceP_mem_chartField
    (h g : Complex[X]) :
    Polynomial.aeval (FhSourceP h) g ∈ FhChartFunctionField h := by
  induction g using Polynomial.induction_on' with
  | add f g hf hg =>
      rw [map_add]
      exact (FhChartFunctionField h).add_mem hf hg
  | monomial n c =>
      rw [Polynomial.aeval_monomial]
      exact (FhChartFunctionField h).mul_mem
        ((FhChartFunctionField h).algebraMap_mem c)
        ((FhChartFunctionField h).pow_mem (FhSourceP_mem_chartField h) n)

theorem sourceDeformation_mem_chartField (h : Complex[X]) :
    sourceDeformation h ∈ FhChartFunctionField h := by
  rw [sourceDeformation_eq_aeval]
  exact aeval_FhSourceP_mem_chartField h h

theorem FhSourcePhi_mem_chartField (h : Complex[X]) :
    FhSourcePhi h ∈ FhChartFunctionField h := by
  unfold FhSourcePhi
  exact (FhChartFunctionField h).add_mem
    ((FhChartFunctionField h).mul_mem
      ((FhChartFunctionField h).mul_mem
        ((FhChartFunctionField h).natCast_mem 3)
        (FhSourceP_mem_chartField h))
      (FhSourceS_mem_chartField h))
    ((FhChartFunctionField h).mul_mem
      ((FhChartFunctionField h).mul_mem
        ((FhChartFunctionField h).pow_mem (FhSourceP_mem_chartField h) 6)
        (sourceDeformation_mem_chartField h))
      ((FhChartFunctionField h).pow_mem (FhSourceS_mem_chartField h) 4))

theorem FhReconstructionY_mem_chartField (h : Complex[X]) :
    FhReconstructionY h ∈ FhChartFunctionField h := by
  unfold FhReconstructionY
  exact (FhChartFunctionField h).sub_mem (FhSourceQ_mem_chartField h)
    (FhSourcePhi_mem_chartField h)

theorem FhReconstructionD_mem_chartField (h : Complex[X]) :
    FhReconstructionD h ∈ FhChartFunctionField h := by
  unfold FhReconstructionD
  exact (FhChartFunctionField h).sub_mem (FhChartFunctionField h).one_mem
    ((FhChartFunctionField h).mul_mem (FhSourceS_mem_chartField h)
      (FhReconstructionY_mem_chartField h))

theorem FhRationalReconstruction_mem_chartField
    (h : Complex[X]) (i : Fin 3) :
    FhRationalReconstruction h i ∈ FhChartFunctionField h := by
  fin_cases i
  · unfold FhRationalReconstruction
    exact (FhChartFunctionField h).div_mem (FhSourceS_mem_chartField h)
      (FhReconstructionD_mem_chartField h)
  · exact FhReconstructionY_mem_chartField h
  · unfold FhRationalReconstruction
    exact (FhChartFunctionField h).sub_mem
      ((FhChartFunctionField h).mul_mem (FhSourceP_mem_chartField h)
        ((FhChartFunctionField h).pow_mem
          (FhReconstructionD_mem_chartField h) 3))
      ((FhChartFunctionField h).mul_mem
        ((FhChartFunctionField h).mul_mem
          ((FhChartFunctionField h).pow_mem
            (FhReconstructionY_mem_chartField h) 2)
          ((FhChartFunctionField h).sub_mem
            ((FhChartFunctionField h).natCast_mem 4)
            ((FhChartFunctionField h).mul_mem (FhSourceS_mem_chartField h)
              (FhReconstructionY_mem_chartField h))))
        (FhReconstructionD_mem_chartField h))

theorem sourceCoordinate_mem_FhChartFunctionField
    (h : Complex[X]) (i : Fin 3) :
    sourceCoordinate i ∈ FhChartFunctionField h := by
  rw [← FhRationalReconstruction_eq_sourceCoordinate h]
  exact FhRationalReconstruction_mem_chartField h i

/-- The rational chart `(s,p,q)` generates the complete source function
field. -/
theorem FhChartFunctionField_eq_top (h : Complex[X]) :
    FhChartFunctionField h = ⊤ := by
  rw [← sourceCoordinateFunctionField_eq_top]
  apply le_antisymm
  · rw [sourceCoordinateFunctionField_eq_top]
    exact le_top
  · exact IntermediateField.adjoin_le_iff.mpr (by
      rintro _ ⟨i, rfl⟩
      exact sourceCoordinate_mem_FhChartFunctionField h i)

/-! ## Algebraic independence and the staged rational-function model -/

/-- Generation by three chart coordinates forces them to be a
transcendence basis: the three canonical source coordinates already give the
matching lower bound on transcendence degree. -/
theorem FhChart_isTranscendenceBasis (h : Complex[X]) :
    IsTranscendenceBasis Complex (FhChartCoordinates h) := by
  letI : Algebra.IsAlgebraic
      (Algebra.adjoin Complex (Set.range (FhChartCoordinates h)))
        SourceFunctionField := by
    constructor
    intro u
    let u' : IntermediateField.adjoin Complex
        (Set.range (FhChartCoordinates h)) :=
      ⟨u, by
        change u ∈ FhChartFunctionField h
        rw [FhChartFunctionField_eq_top h]
        trivial⟩
    have hu' : IsAlgebraic
        (Algebra.adjoin Complex (Set.range (FhChartCoordinates h))) u' :=
      Algebra.IsAlgebraic.isAlgebraic u'
    have hmap := (isAlgebraic_algebraMap_iff
      (algebraMap (IntermediateField.adjoin Complex
        (Set.range (FhChartCoordinates h))) SourceFunctionField).injective).2 hu'
    exact hmap
  exact Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite
    Complex (FhChartCoordinates h)
      sourceCoordinate_algebraicIndependent.cardinalMk_le_trdeg

theorem FhChart_algebraicIndependent (h : Complex[X]) :
    AlgebraicIndependent Complex (FhChartCoordinates h) :=
  (FhChart_isTranscendenceBasis h).1

/-- The coefficient subfield `Complex(p,q)` inside the source field. -/
def FhParameterFunctionField (h : Complex[X]) :
    IntermediateField Complex SourceFunctionField :=
  IntermediateField.adjoin Complex
    (FhChartCoordinates h '' ({1, 2} : Set (Fin 3)))

theorem FhSourceS_transcendental (h : Complex[X]) :
    Transcendental
      (Algebra.adjoin Complex
        (FhChartCoordinates h '' ({1, 2} : Set (Fin 3)))) FhSourceS := by
  exact (FhChart_algebraicIndependent h).transcendental_adjoin
    (s := ({1, 2} : Set (Fin 3))) (i := 0) (by simp)

/-- Birational chart automorphism sending the canonical ordered source
coordinates to `(s,p,q)`. -/
noncomputable def FhChartAutomorphism (h : Complex[X]) :
    SourceFunctionField ≃ₐ[Complex] SourceFunctionField :=
  (FhChart_algebraicIndependent h).aevalEquivField |>.trans
    ((IntermediateField.equivOfEq (FhChartFunctionField_eq_top h)).trans
      IntermediateField.topEquiv)

@[simp] theorem FhChartAutomorphism_sourceCoordinate
    (h : Complex[X]) (i : Fin 3) :
    FhChartAutomorphism h (sourceCoordinate i) = FhChartCoordinates h i := by
  change FhChartAutomorphism h
      (DegreeSixKeller.FunctionFieldSpike.sourceCoordinate i) = _
  rw [DegreeSixKeller.FunctionFieldSpike.sourceCoordinate_eq_algebraMap]
  change ((↑((FhChart_algebraicIndependent h).aevalEquivField
      (algebraMap (MvPolynomial (Fin 3) Complex) SourceFunctionField
        (MvPolynomial.X i))) : SourceFunctionField)) = FhChartCoordinates h i
  rw [AlgebraicIndependent.aevalEquivField_algebraMap_apply_coe]
  simp

@[simp] theorem FhChartAutomorphism_symm_chartCoordinate
    (h : Complex[X]) (i : Fin 3) :
    (FhChartAutomorphism h).symm (FhChartCoordinates h i) =
      sourceCoordinate i := by
  rw [← FhChartAutomorphism_sourceCoordinate h i]
  exact (FhChartAutomorphism h).symm_apply_apply _

/-- The production chart comparison with the staged `Complex(p,q)(s)`
rational-function field. -/
noncomputable def FhChartToRatFuncEquiv (h : Complex[X]) :
    SourceFunctionField ≃ₐ[Complex] SimpleExtensionFunctionField :=
  (FhChartAutomorphism h).symm.trans
    sourceFunctionFieldFinSuccToRatFuncEquiv

@[simp] theorem sourceFunctionFieldFinSuccToRatFuncEquiv_coordinate_succ
    (i : Fin 2) :
    sourceFunctionFieldFinSuccToRatFuncEquiv (sourceCoordinate i.succ) =
      algebraMap ParameterFunctionField SimpleExtensionFunctionField
        (parameterCoordinate i) := by
  change sourceFunctionFieldFinSuccToRatFuncEquiv
      (DegreeSixKeller.FunctionFieldSpike.sourceCoordinate i.succ) = _
  rw [DegreeSixKeller.FunctionFieldSpike.sourceCoordinate_eq_algebraMap]
  simp [sourceFunctionFieldFinSuccToRatFuncEquiv,
    sourceFractionFinSuccEquiv, sourcePolynomialFinSuccEquiv,
    splitFractionToRatFuncEquiv,
    MvPolynomial.finSuccEquiv_X_succ, parameterCoordinate,
    parameterPolynomialInclusion]
  change splitPolynomialToRatFuncRingHom
      (Polynomial.C (MvPolynomial.X i)) =
    RatFunc.C
      (algebraMap ParameterPolynomialRing ParameterFunctionField
        (MvPolynomial.X i))
  simp [splitPolynomialToRatFuncRingHom]

@[simp] theorem FhChartToRatFuncEquiv_sourceS (h : Complex[X]) :
    FhChartToRatFuncEquiv h FhSourceS = RatFunc.X := by
  change FhChartToRatFuncEquiv h (FhChartCoordinates h 0) = RatFunc.X
  rw [FhChartToRatFuncEquiv, AlgEquiv.trans_apply,
    FhChartAutomorphism_symm_chartCoordinate]
  exact sourceFunctionFieldFinSuccToRatFuncEquiv_coordinate_zero

@[simp] theorem FhChartToRatFuncEquiv_sourceP (h : Complex[X]) :
    FhChartToRatFuncEquiv h (FhSourceP h) =
      algebraMap ParameterFunctionField SimpleExtensionFunctionField p := by
  change FhChartToRatFuncEquiv h (FhChartCoordinates h 1) = _
  simpa [FhChartToRatFuncEquiv, p] using
    sourceFunctionFieldFinSuccToRatFuncEquiv_coordinate_succ (i := (0 : Fin 2))

@[simp] theorem FhChartToRatFuncEquiv_sourceQ (h : Complex[X]) :
    FhChartToRatFuncEquiv h (FhSourceQ h) =
      algebraMap ParameterFunctionField SimpleExtensionFunctionField q := by
  change FhChartToRatFuncEquiv h (FhChartCoordinates h 2) = _
  simpa [FhChartToRatFuncEquiv, q] using
    sourceFunctionFieldFinSuccToRatFuncEquiv_coordinate_succ (i := (1 : Fin 2))

theorem FhChartToRatFuncEquiv_aeval
    (h g : Complex[X]) :
    FhChartToRatFuncEquiv h (Polynomial.aeval (FhSourceP h) g) =
      algebraMap ParameterFunctionField SimpleExtensionFunctionField
        (Polynomial.aeval p g) := by
  induction g using Polynomial.induction_on' with
  | add f g hf hg =>
      simp only [map_add, hf, hg]
  | monomial n c =>
      rw [Polynomial.aeval_monomial, Polynomial.aeval_monomial,
        map_mul, map_pow, FhChartToRatFuncEquiv_sourceP,
        map_mul, map_pow]
      rw [(FhChartToRatFuncEquiv h).commutes c]
      rw [IsScalarTower.algebraMap_apply Complex ParameterFunctionField
        SimpleExtensionFunctionField]

@[simp] theorem FhChartToRatFuncEquiv_sourceDeformation
    (h : Complex[X]) :
    FhChartToRatFuncEquiv h (sourceDeformation h) =
      algebraMap ParameterFunctionField SimpleExtensionFunctionField
        (evaluateAtP h) := by
  rw [sourceDeformation_eq_aeval]
  simpa [evaluateAtP] using FhChartToRatFuncEquiv_aeval h h

set_option maxHeartbeats 800000 in
@[simp] theorem FhChartToRatFuncEquiv_sourceR (h : Complex[X]) :
    FhChartToRatFuncEquiv h (FhSourceR h) = inverseGenerator h := by
  have htwo : FhChartToRatFuncEquiv h (2 : SourceFunctionField) =
      (2 : SimpleExtensionFunctionField) := by
    exact map_ofNat (FhChartToRatFuncEquiv h) 2
  have hthird : FhChartToRatFuncEquiv h
      (1 / 3 : SourceFunctionField) =
      (1 / 3 : SimpleExtensionFunctionField) := by
    calc
      FhChartToRatFuncEquiv h (1 / 3 : SourceFunctionField) =
          (3 : SimpleExtensionFunctionField)⁻¹ := by
        simpa using
          (map_ratCast (FhChartToRatFuncEquiv h) (1 / 3 : ℚ))
      _ = (1 / 3 : SimpleExtensionFunctionField) :=
        (one_div (3 : SimpleExtensionFunctionField)).symm
  have hKthird :
      algebraMap ParameterFunctionField SimpleExtensionFunctionField
          (1 / 3 : ParameterFunctionField) =
        (1 / 3 : SimpleExtensionFunctionField) := by
    calc
      algebraMap ParameterFunctionField SimpleExtensionFunctionField
          (1 / 3 : ParameterFunctionField) =
          (3 : SimpleExtensionFunctionField)⁻¹ := by
        simpa using (map_ratCast
          (algebraMap ParameterFunctionField SimpleExtensionFunctionField)
            (1 / 3 : ℚ))
      _ = (1 / 3 : SimpleExtensionFunctionField) :=
        (one_div (3 : SimpleExtensionFunctionField)).symm
  rw [FhSourceR_inverseEquation]
  simp only [map_add, map_sub, map_mul, map_pow,
    FhChartToRatFuncEquiv_sourceP, FhChartToRatFuncEquiv_sourceQ,
    FhChartToRatFuncEquiv_sourceS,
    FhChartToRatFuncEquiv_sourceDeformation]
  rw [htwo, hthird]
  unfold inverseGenerator inversePolynomial inverseLeadingCoefficient
  simp only [map_add, map_sub, map_mul, map_pow,
    RatFunc.algebraMap_C, RatFunc.algebraMap_X]
  rw [← RatFunc.algebraMap_eq_C,
    map_ofNat
      (algebraMap ParameterFunctionField SimpleExtensionFunctionField) 2,
    hKthird]

/-- The coordinate-generated field after transporting the rational chart to
`Complex(p,q)(s)`. -/
def FhRatFuncCoordinateField (h : Complex[X]) :
    IntermediateField Complex SimpleExtensionFunctionField :=
  IntermediateField.adjoin Complex
    {algebraMap ParameterFunctionField SimpleExtensionFunctionField p,
      algebraMap ParameterFunctionField SimpleExtensionFunctionField q,
      inverseGenerator h}

theorem coordinateFunctionField_map_FhChartToRatFuncEquiv
    (h : Complex[X]) :
    (coordinateFunctionField (FhPolynomial h)).map
        (FhChartToRatFuncEquiv h).toAlgHom =
      FhRatFuncCoordinateField h := by
  rw [coordinateFunctionField, IntermediateField.adjoin_map]
  congr 1
  ext z
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
    fin_cases i
    · left
      exact FhChartToRatFuncEquiv_sourceP h
    · right; left
      exact FhChartToRatFuncEquiv_sourceQ h
    · right; right
      exact FhChartToRatFuncEquiv_sourceR h
  · rintro (rfl | rfl | rfl)
    · exact ⟨coordinateRationalFunction (FhPolynomial h) 0,
        ⟨0, rfl⟩, FhChartToRatFuncEquiv_sourceP h⟩
    · exact ⟨coordinateRationalFunction (FhPolynomial h) 1,
        ⟨1, rfl⟩, FhChartToRatFuncEquiv_sourceQ h⟩
    · exact ⟨coordinateRationalFunction (FhPolynomial h) 2,
        ⟨2, rfl⟩, FhChartToRatFuncEquiv_sourceR h⟩

private theorem parameterPolynomial_mem_FhRatFuncCoordinateField
    (h : Complex[X]) (f : ParameterPolynomialRing) :
    algebraMap ParameterFunctionField SimpleExtensionFunctionField
        (parameterPolynomialInclusion f) ∈ FhRatFuncCoordinateField h := by
  induction f using MvPolynomial.induction_on with
  | C c =>
      simpa [parameterPolynomialInclusion,
        IsScalarTower.algebraMap_apply Complex ParameterFunctionField
          SimpleExtensionFunctionField] using
        (FhRatFuncCoordinateField h).algebraMap_mem c
  | add f g hf hg =>
      simp only [map_add]
      exact (FhRatFuncCoordinateField h).add_mem hf hg
  | mul_X f i hf =>
      simp only [map_mul]
      apply (FhRatFuncCoordinateField h).mul_mem hf
      change algebraMap ParameterFunctionField SimpleExtensionFunctionField
          (parameterCoordinate i) ∈ FhRatFuncCoordinateField h
      fin_cases i
      · exact IntermediateField.subset_adjoin Complex _ (by simp [p])
      · exact IntermediateField.subset_adjoin Complex _ (by simp [q])

theorem parameterFunction_mem_FhRatFuncCoordinateField
    (h : Complex[X]) (f : ParameterFunctionField) :
    algebraMap ParameterFunctionField SimpleExtensionFunctionField f ∈
      FhRatFuncCoordinateField h := by
  obtain ⟨a, b, _hb, rfl⟩ :=
    IsFractionRing.div_surjective ParameterPolynomialRing f
  rw [show
    algebraMap ParameterFunctionField SimpleExtensionFunctionField
        (algebraMap ParameterPolynomialRing ParameterFunctionField a /
          algebraMap ParameterPolynomialRing ParameterFunctionField b) =
      algebraMap ParameterFunctionField SimpleExtensionFunctionField
          (algebraMap ParameterPolynomialRing ParameterFunctionField a) /
        algebraMap ParameterFunctionField SimpleExtensionFunctionField
          (algebraMap ParameterPolynomialRing ParameterFunctionField b) from
    _root_.map_div₀
      (algebraMap ParameterFunctionField SimpleExtensionFunctionField) _ _]
  exact (FhRatFuncCoordinateField h).div_mem
    (parameterPolynomial_mem_FhRatFuncCoordinateField h a)
    (parameterPolynomial_mem_FhRatFuncCoordinateField h b)

/-- The transported coordinate field is exactly `Complex(p,q)(r)`, i.e. the
restriction to `Complex` of the intermediate field generated by the inverse
generator over `Complex(p,q)`. -/
theorem FhRatFuncCoordinateField_eq_generatedIntermediateField
    (h : Complex[X]) :
    FhRatFuncCoordinateField h =
      (generatedIntermediateField (inverseGenerator h)).restrictScalars
        Complex := by
  ext z
  constructor
  · intro hz
    apply (IntermediateField.adjoin_le_iff.mpr ?_) hz
    rintro _ (rfl | rfl | rfl)
    · exact (generatedIntermediateField (inverseGenerator h)).algebraMap_mem p
    · exact (generatedIntermediateField (inverseGenerator h)).algebraMap_mem q
    · exact IntermediateField.subset_adjoin ParameterFunctionField
        {inverseGenerator h} (by simp)
  · intro hz
    let promoted :
        IntermediateField ParameterFunctionField
          SimpleExtensionFunctionField :=
      { (FhRatFuncCoordinateField h).toSubfield with
        algebraMap_mem' := parameterFunction_mem_FhRatFuncCoordinateField h }
    have hgenerated :
        generatedIntermediateField (inverseGenerator h) ≤ promoted := by
      apply IntermediateField.adjoin_le_iff.mpr
      intro z hz
      simp only [Set.mem_singleton_iff] at hz
      subst z
      change inverseGenerator h ∈ FhRatFuncCoordinateField h
      exact IntermediateField.subset_adjoin Complex _ (by simp)
    exact hgenerated hz

/-! ## Generic degree of the family -/

/-- The genuine function-field degree of every nontrivial member of the
degree-six family is six. -/
theorem Fh_genericDegree_six (h : Complex[X]) (hh : h ≠ 0) :
    genericDegree (FhPolynomial h) = 6 := by
  let e := FhChartToRatFuncEquiv h
  have hcomap :
      (FhRatFuncCoordinateField h).comap e.toAlgHom =
        coordinateFunctionField (FhPolynomial h) := by
    rw [← coordinateFunctionField_map_FhChartToRatFuncEquiv h]
    rw [IntermediateField.comap_map]
  calc
    genericDegree (FhPolynomial h) =
        Module.finrank
          ((FhRatFuncCoordinateField h).comap e.toAlgHom)
          SourceFunctionField := by
      rw [genericDegree, hcomap]
    _ = IntermediateField.relfinrank (FhRatFuncCoordinateField h)
          e.toAlgHom.fieldRange :=
      IntermediateField.finrank_comap (FhRatFuncCoordinateField h) e.toAlgHom
    _ = IntermediateField.relfinrank (FhRatFuncCoordinateField h)
          (⊤ : IntermediateField Complex SimpleExtensionFunctionField) := by
      rw [AlgEquiv.fieldRange_eq_top e]
    _ = Module.finrank (FhRatFuncCoordinateField h)
          SimpleExtensionFunctionField :=
      IntermediateField.relfinrank_top_right
        (F := Complex) (E := SimpleExtensionFunctionField)
        (FhRatFuncCoordinateField h)
    _ = Module.finrank
          (generatedIntermediateField (inverseGenerator h))
          SimpleExtensionFunctionField := by
      rw [FhRatFuncCoordinateField_eq_generatedIntermediateField]
      rfl
    _ = 6 := inverseGenerator_finrank hh

theorem eta004_ne_zero : eta004 ≠ 0 := by
  intro hzero
  have heval := congrArg (fun f : Complex[X] => f.eval 0) hzero
  norm_num [eta004] at heval

theorem eta006_ne_zero : eta006 ≠ 0 := by
  intro hzero
  have heval := congrArg (fun f : Complex[X] => f.eval 0) hzero
  norm_num [eta006] at heval

theorem F004_genericDegree_six : genericDegree F004Polynomial = 6 := by
  simpa [F004Polynomial] using Fh_genericDegree_six eta004 eta004_ne_zero

theorem F006_genericDegree_six : genericDegree F006Polynomial = 6 := by
  simpa [F006Polynomial] using Fh_genericDegree_six eta006 eta006_ne_zero

end GenericDegree

export GenericDegree
  (SourceFunctionField sourcePolynomialInclusion sourceCoordinate
    coordinateRationalFunction coordinateFunctionField genericDegree
    sourceCoordinateFunctionField sourceCoordinateFunctionField_eq_top
    Fh_genericDegree_six eta004_ne_zero eta006_ne_zero
    F004_genericDegree_six F006_genericDegree_six)

end

end DegreeSixKeller
